services:

  postgres:
    image: postgres:17
    container_name: smart-parking-postgres

    environment:
      POSTGRES_DB: smartparking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: smart-parking-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: smart-parking-grafana

    ports:
      - "3000:3000"

    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin

    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      - prometheus

    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management
    container_name: lindvior-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

    ports:
      - "5672:5672"
      - "15672:15672"

    restart: unless-stopped

volumes:
  postgres_data:
  prometheus_data:
  grafana_data: