spring:
  application:
    name: Lindvior

  profiles:
    active: dev

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 100

  kafka:
    bootstrap-servers: localhost:9094

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: lindvior-notification
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.rick.smartparkingplatform.notification


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
          - beans
          - conditions

  endpoint:
    health:
      show-details: always

jwt:
  secret-key: LindviorSecretSmartParkingPlatformDevelopment2026JWT
  expiration: 86400000

application:
  version: 1.0.0